name: Deploy Crm

on:
  pull_request:
    branches:
      - dev  
  push:
    branches:
      - dev  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Switch to root user
            sudo -i

            # Check if the repository exists, if not clone the dev branch directly
            git clone -b dev git@github.com:DingDingHouse/ding-ding-crm-nextjs.git
            
            cd /root/ding-ding-crm-nextjs
            git checkout dev
            git pull origin dev

            # Build the new Docker image without stopping the running containers
            docker-compose build

            # After the image is built, stop the existing containers and immediately start the new ones
            docker-compose down
            docker-compose up -d

            # Clean up unused Docker images and containers 
            docker image prune -f
          EOF
